
import { Product } from './types';

export const CATEGORIES = ['All', 'Smart Home', 'Wearables', 'Lifestyle', 'Gaming', 'Office'];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Smart Ambient Lamp',
    description: 'A touch-controlled LED lamp with 16 million colors and smartphone integration.',
    price: 3699,
    oldPrice: 4799,
    category: 'Smart Home',
    images: ['https://picsum.photos/seed/lamp/600/600'],
    rating: 4.8,
    reviewsCount: 124,
    stock: 50,
    isFeatured: true,
    tags: ['tech', 'decor', 'gift'],
    brand: 'TG Original',
    deliveryCharge: 0,
    status: 'Active',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z'
  },
  {
    id: 'p2',
    name: 'Wireless Ergonomic Mouse',
    description: 'Precision tracking and comfortable grip for long hours of productivity.',
    price: 2399,
    category: 'Office',
    images: ['https://picsum.photos/seed/mouse/600/600'],
    rating: 4.5,
    reviewsCount: 89,
    stock: 120,
    isFeatured: true,
    tags: ['productivity', 'work', 'minimalist'],
    brand: 'TG Original',
    deliveryCharge: 0,
    status: 'Active',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z'
  },
  {
    id: 'p3',
    name: 'Retro Mechanical Keyboard',
    description: 'Tactile switches with a classic typewriter aesthetic and modern RGB backlighting.',
    price: 7120,
    oldPrice: 8800,
    category: 'Gaming',
    images: ['https://picsum.photos/seed/keyboard/600/600'],
    rating: 4.9,
    reviewsCount: 210,
    stock: 15,
    isFeatured: true,
    tags: ['retro', 'gaming', 'premium'],
    brand: 'TG Original',
    deliveryCharge: 0,
    status: 'Active',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z'
  },
  {
    id: 'p4',
    name: 'Portable Mini Projector',
    description: 'Turn any wall into a cinema with this 1080p supported compact projector.',
    price: 15999,
    category: 'Lifestyle',
    images: ['https://picsum.photos/seed/projector/600/600'],
    rating: 4.6,
    reviewsCount: 56,
    stock: 30,
    isFeatured: false,
    tags: ['entertainment', 'travel'],
    brand: 'TG Original',
    deliveryCharge: 0,
    status: 'Active',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z'
  },
  {
    id: 'p5',
    name: 'Fitness Smart Watch V2',
    description: 'Monitor your health metrics, track workouts, and stay connected on the go.',
    price: 10360,
    category: 'Wearables',
    images: ['https://picsum.photos/seed/watch/600/600'],
    rating: 4.7,
    reviewsCount: 178,
    stock: 45,
    isFeatured: true,
    tags: ['fitness', 'health', 'tech'],
    brand: 'TG Original',
    deliveryCharge: 0,
    status: 'Active',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z'
  },
  {
    id: 'p6',
    name: 'Noise Cancelling Buds',
    description: 'Immersive sound quality with active noise cancellation and 24-hour battery life.',
    price: 6399,
    oldPrice: 7999,
    category: 'Wearables',
    images: ['https://picsum.photos/seed/buds/600/600'],
    rating: 4.4,
    reviewsCount: 342,
    stock: 80,
    isFeatured: false,
    tags: ['audio', 'music', 'portable'],
    brand: 'TG Original',
    deliveryCharge: 0,
    status: 'Active',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z'
  }
];
